spring:
  profiles:
    active: test
 #devtools
  devtools:
    restart:
      enabled: true

#mybatis
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.swg.dao
rocketmq:
  name:
    server:
      address: 127.0.0.1
